### PR TITLE
Us70 customer nested

### PR DESCRIPTION
**Pull request by maggieli321**

### CODE REVIEW

**Comment by achalc** [comment]
so does everything work for this now?

**Comment by maggieli321** [comment]
Only thing left is to figure out how to save/set request_id again if page is refreshed from input error.

**Comment by achalc** [comment]
Yeah I already fixed that

## 

Achal Channarasappa
(412) 491-0128

**Comment by achalc** [comment]
Wait I don't think request_id will pose an issue on the customer nested form. Does it?

## 

Achal Channarasappa
(412) 491-0128

**Pull request merged**
