### PR TITLE
US73 - fixed name link to redirect back to request page instead of email on cus...

### PR DESCRIPTION
**Pull request by maggieli321**
...tomer index page

### CODE REVIEW

**Comment by achalc** [comment]
I made this a link to email the point of contact on purpose

**Comment by maggieli321** [comment]
Oh, it was one of the items on Trello to change back - I think Ryan wanted to just have it link to the same page as the other two buttons. I forget why but we can ask him.

**Comment by rdonegan** [comment]
Kat, Maggie, and I talked about this and we felt that it was a little unexpected and inconsistent with other table links to have that functionality. On all other tables, the links direct to a details page, and there's no clear indication that this link is going to open an email. I think having a link to a contact's email is good to have, but it should probably be on the details page just to avoid confusion.

**Comment by maggieli321** [comment]
I think we can include the email link as well - we can just add an extra column and the link can be called "Send email." We can ask Teresa and Ross if they would like this functionality added on Friday.

**Pull request merged**
